# Generated by Django 5.1.3 on 2024-11-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('types', models.CharField(max_length=200)),
                ('weight', models.IntegerField()),
                ('abilities', models.CharField(max_length=300)),
                ('image_front', models.URLField()),
                ('image_back', models.URLField()),
            ],
        ),
    ]
